# Generated by Django 3.2.25 on 2025-01-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db_meta", "0043_auto_20241106_1704"),
        ("db_meta", "0045_alter_polarisentrydetail_polaris_name"),
    ]

    operations = []
